baseURL="https://www.huskyhoochu.com/"
languageCode = "ko-kr"
title = "HuskyHoochu 기술 블로그"
hasCJKLanguage = true
pygmentsStyle = "pastie"

[taxonomies]
tag = "tags"
author = "authors"
subtitle = "subtitles"
